FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        autoconf \
        build-essential \
        bzip2 \
        cmake \
        cython3 \
        git \
        libbz2-dev \
        libncurses5-dev \
        openjdk-8-jdk \
        pkg-config \
        python3-dev \
        python3-setuptools \
        python3-pip \
        software-properties-common \
        wget \
        zlib1g-dev \
        libboost-all-dev && \
    apt-get clean -y

# copy git repository into the image
RUN mkdir -p /opt/hap.py-source
COPY . /opt/hap.py-source/

# make minimal HG19 reference sequence
RUN mkdir -p /opt/hap.py-data

# get + install ant
# WORKDIR /opt
# RUN wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.7-bin.tar.gz && \
#     tar xzf apache-ant-1.9.7-bin.tar.gz && \
#     rm apache-ant-1.9.7-bin.tar.gz
# ENV PATH $PATH:/opt/apache-ant-1.9.7/bin

# run hap.py installer in the image, run tests since we have a reference file
WORKDIR /opt/hap.py-source
RUN python3 install.py /opt/hap.py --with-rtgtools --ignore-test-failures

# download HG19 reference data
# This downloads from UCSC
WORKDIR /opt/hap.py-data
ENV PATH $PATH:/opt/hap.py/bin
RUN /opt/hap.py-source/src/sh/make_hg19.sh && samtools faidx /opt/hap.py-data/hg19.fa
# Run tests
ENV HG19 /opt/hap.py-data/hg19.fa
WORKDIR /opt/hap.py
RUN /opt/hap.py-source/src/sh/run_tests.sh

# remove source folder
WORKDIR /
RUN rm -rf /opt/hap.py-source
