name: hap-py
channels:
  - bioconda
  - conda-forge
dependencies:
  - rtg-tools=3.13
  - python=3.11
  - numpy
  - pandas
  - psutil
  - pysam
  - scipy
  - bx-python
  - biopython
  - htslib
  - pip
  - pip:
      - .[cpp]

## Env for dev - might want a separate yml for this
# name: happy-dev
# channels:
#   - conda-forge
# dependencies:
#   - python=3.11
#  - cmake
#  - gcc
#  - make
#  - zlib
#  - boost
#  - pip:
#      - '.[dev,cpp]'
