name: hap-py
channels:
  - bioconda
  - conda-forge
dependencies:
  - rtg-tools=3.13
  - python=3.11
  - numpy
  - pandas
  - psutil
  - pysam
  - scipy
  - bx-python
  - biopython
  - htslib
  - pip
  - bcftools
  - matplotlib
  - seaborn
  - scikit-learn
  - pytest
  - pytest-cov
  - pytest-benchmark
  - nose
