[mypy]
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
# Only enforce typing on core modernization modules for now
files = src/python/happy/hap.py, src/python/Haplo/vcfeval.py
